<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>


    <PropertyGroup>
        <Company>cbhacks</Company>
        <Description>Unofficial Crash Bandicoot 1/2/3 Level Editor</Description>
        <AssemblyTitle>CrashEdit 'Main' module</AssemblyTitle>
        <Version>2.0.0</Version>
    </PropertyGroup>

    <ItemGroup>
      <FrameworkReference Include="Microsoft.WindowsDesktop.App" />
      <Compile Remove="FTBitmapExtensions\**" />
      <Compile Remove="Crash.UI\**" />
      <Compile Remove="CrashEdit\**" />
      <Compile Remove="CrashHacks\**" />
      <Compile Remove="ISO2PSX\**" />
      <EmbeddedResource Remove="FTBitmapExtensions\**" />
      <EmbeddedResource Remove="Crash.UI\**" />
      <EmbeddedResource Remove="CrashEdit\**" />
      <EmbeddedResource Remove="CrashHacks\**" />
      <EmbeddedResource Remove="ISO2PSX\**" />
      <None Remove="FTBitmapExtensions\**" />
      <None Remove="Crash.UI\**" />
      <None Remove="CrashEdit\**" />
      <None Remove="CrashHacks\**" />
      <None Remove="ISO2PSX\**" />
    </ItemGroup>

    <ItemGroup>
      <None Remove=".gitignore" />
      <None Remove="Embeds\Images\Add.png" />
      <None Remove="Embeds\Images\Anchor.png" />
      <None Remove="Embeds\Images\Application.png" />
      <None Remove="Embeds\Images\Arrow.png" />
      <None Remove="Embeds\Images\ArrowRefresh.png" />
      <None Remove="Embeds\Images\Calculator.png" />
      <None Remove="Embeds\Images\CD.png" />
      <None Remove="Embeds\Images\Container.png" />
      <None Remove="Embeds\Images\Controller.png" />
      <None Remove="Embeds\Images\Copy.png" />
      <None Remove="Embeds\Images\Cut.png" />
      <None Remove="Embeds\Images\Dropdown.png" />
      <None Remove="Embeds\Images\Earth.png" />
      <None Remove="Embeds\Images\Erase.png" />
      <None Remove="Embeds\Images\Export.png" />
      <None Remove="Embeds\Images\File.png" />
      <None Remove="Embeds\Images\Filter.png" />
      <None Remove="Embeds\Images\Find.png" />
      <None Remove="Embeds\Images\First.png" />
      <None Remove="Embeds\Images\Floppy.png" />
      <None Remove="Embeds\Images\Floppy2.png" />
      <None Remove="Embeds\Images\Folder.png" />
      <None Remove="Embeds\Images\FolderOpen.png" />
      <None Remove="Embeds\Images\HardDisk.png" />
      <None Remove="Embeds\Images\HelpSymbol.png" />
      <None Remove="Embeds\Images\Hint.png" />
      <None Remove="Embeds\Images\Import.png" />
      <None Remove="Embeds\Images\ImportPlus.png" />
      <None Remove="Embeds\Images\JournalBlue.gif" />
      <None Remove="Embeds\Images\JournalCode.gif" />
      <None Remove="Embeds\Images\JournalCyan.gif" />
      <None Remove="Embeds\Images\JournalOrange.gif" />
      <None Remove="Embeds\Images\JournalRed.gif" />
      <None Remove="Embeds\Images\JournalWhite.gif" />
      <None Remove="Embeds\Images\JournalGray.gif" />
      <None Remove="Embeds\Images\Last.png" />
      <None Remove="Embeds\Images\Lightning.png" />
      <None Remove="Embeds\Images\List.png" />
      <None Remove="Embeds\Images\Modify.png" />
      <None Remove="Embeds\Images\MusicNoteBlue.png" />
      <None Remove="Embeds\Images\MusicNoteRed.png" />
      <None Remove="Embeds\Images\MusicNoteYellow.png" />
      <None Remove="Embeds\Images\Next.png" />
      <None Remove="Embeds\Images\NSD.png" />
      <None Remove="Embeds\Images\NSF.png" />
      <None Remove="Embeds\Images\Painting.gif" />
      <None Remove="Embeds\Images\Paste.png" />
      <None Remove="Embeds\Images\Pinion.png" />
      <None Remove="Embeds\Images\Playstation.png" />
      <None Remove="Embeds\Images\Plugin.png" />
      <None Remove="Embeds\Images\PluginDisabled.png" />
      <None Remove="Embeds\Images\Previous.png" />
      <None Remove="Embeds\Images\Processor.png" />
      <None Remove="Embeds\Images\README.md" />
      <None Remove="Embeds\Images\Sitemap.png" />
      <None Remove="Embeds\Images\SpeakerBlue.png" />
      <None Remove="Embeds\Images\SpeakerWhite.png" />
      <None Remove="Embeds\Images\ThingBlue.gif" />
      <None Remove="Embeds\Images\ThingCode.gif" />
      <None Remove="Embeds\Images\ThingCrimson.gif" />
      <None Remove="Embeds\Images\ThingGray.gif" />
      <None Remove="Embeds\Images\ThingLime.gif" />
      <None Remove="Embeds\Images\ThingOrange.gif" />
      <None Remove="Embeds\Images\ThingRed.gif" />
      <None Remove="Embeds\Images\ThingViolet.gif" />
      <None Remove="Embeds\Images\ThingYellow.gif" />
      <None Remove="Embeds\Images\Wrench.png" />
      <None Remove="LICENSE.md" />
      <None Remove="packages.config" />
      <None Remove="README.md" />
    </ItemGroup>

    <ItemGroup>
      <Compile Include="CrashEdit\Properties\Settings.Designer.cs" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Include="Embeds\Images\Add.png" />
      <EmbeddedResource Include="Embeds\Images\Anchor.png" />
      <EmbeddedResource Include="Embeds\Images\Application.png" />
      <EmbeddedResource Include="Embeds\Images\Arrow.png" />
      <EmbeddedResource Include="Embeds\Images\ArrowRefresh.png" />
      <EmbeddedResource Include="Embeds\Images\Calculator.png" />
      <EmbeddedResource Include="Embeds\Images\CD.png" />
      <EmbeddedResource Include="Embeds\Images\Container.png" />
      <EmbeddedResource Include="Embeds\Images\Controller.png" />
      <EmbeddedResource Include="Embeds\Images\Copy.png" />
      <EmbeddedResource Include="Embeds\Images\Cut.png" />
      <EmbeddedResource Include="Embeds\Images\Dropdown.png" />
      <EmbeddedResource Include="Embeds\Images\Earth.png" />
      <EmbeddedResource Include="Embeds\Images\Erase.png" />
      <EmbeddedResource Include="Embeds\Images\Export.png" />
      <EmbeddedResource Include="Embeds\Images\File.png" />
      <EmbeddedResource Include="Embeds\Images\Filter.png" />
      <EmbeddedResource Include="Embeds\Images\Find.png" />
      <EmbeddedResource Include="Embeds\Images\First.png" />
      <EmbeddedResource Include="Embeds\Images\Floppy.png" />
      <EmbeddedResource Include="Embeds\Images\Floppy2.png" />
      <EmbeddedResource Include="Embeds\Images\Folder.png" />
      <EmbeddedResource Include="Embeds\Images\FolderOpen.png" />
      <EmbeddedResource Include="Embeds\Images\HardDisk.png" />
      <EmbeddedResource Include="Embeds\Images\HelpSymbol.png" />
      <EmbeddedResource Include="Embeds\Images\Hint.png" />
      <EmbeddedResource Include="Embeds\Images\Import.png" />
      <EmbeddedResource Include="Embeds\Images\ImportPlus.png" />
      <EmbeddedResource Include="Embeds\Images\JournalBlue.gif" />
      <EmbeddedResource Include="Embeds\Images\JournalCode.gif" />
      <EmbeddedResource Include="Embeds\Images\JournalCyan.gif" />
      <EmbeddedResource Include="Embeds\Images\JournalOrange.gif" />
      <EmbeddedResource Include="Embeds\Images\JournalRed.gif" />
      <EmbeddedResource Include="Embeds\Images\JournalWhite.gif" />
      <EmbeddedResource Include="Embeds\Images\JournalGray.gif" />
      <EmbeddedResource Include="Embeds\Images\Last.png" />
      <EmbeddedResource Include="Embeds\Images\Lightning.png" />
      <EmbeddedResource Include="Embeds\Images\List.png" />
      <EmbeddedResource Include="Embeds\Images\Modify.png" />
      <EmbeddedResource Include="Embeds\Images\MusicNoteBlue.png" />
      <EmbeddedResource Include="Embeds\Images\MusicNoteRed.png" />
      <EmbeddedResource Include="Embeds\Images\MusicNoteYellow.png" />
      <EmbeddedResource Include="Embeds\Images\Next.png" />
      <EmbeddedResource Include="Embeds\Images\NSD.png" />
      <EmbeddedResource Include="Embeds\Images\NSF.png" />
      <EmbeddedResource Include="Embeds\Images\Painting.gif" />
      <EmbeddedResource Include="Embeds\Images\Paste.png" />
      <EmbeddedResource Include="Embeds\Images\Pinion.png" />
      <EmbeddedResource Include="Embeds\Images\Playstation.png" />
      <EmbeddedResource Include="Embeds\Images\Plugin.png" />
      <EmbeddedResource Include="Embeds\Images\PluginDisabled.png" />
      <EmbeddedResource Include="Embeds\Images\Previous.png" />
      <EmbeddedResource Include="Embeds\Images\Processor.png" />
      <EmbeddedResource Include="Embeds\Images\Sitemap.png" />
      <EmbeddedResource Include="Embeds\Images\SpeakerBlue.png" />
      <EmbeddedResource Include="Embeds\Images\SpeakerWhite.png" />
      <EmbeddedResource Include="Embeds\Images\ThingBlue.gif" />
      <EmbeddedResource Include="Embeds\Images\ThingCode.gif" />
      <EmbeddedResource Include="Embeds\Images\ThingCrimson.gif" />
      <EmbeddedResource Include="Embeds\Images\ThingGray.gif" />
      <EmbeddedResource Include="Embeds\Images\ThingLime.gif" />
      <EmbeddedResource Include="Embeds\Images\ThingOrange.gif" />
      <EmbeddedResource Include="Embeds\Images\ThingRed.gif" />
      <EmbeddedResource Include="Embeds\Images\ThingViolet.gif" />
      <EmbeddedResource Include="Embeds\Images\ThingYellow.gif" />
      <EmbeddedResource Include="Embeds\Images\Wrench.png" />
    </ItemGroup>

    <ItemGroup>
      <None Include=".github\copilot-instructions.md" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="AltUI" Version="1.0.4" />
      <PackageReference Include="MetroSetUI" Version="1.0.11" />
    </ItemGroup>

	<PropertyGroup>
		<NoWarn>WFO1000; WFO5001</NoWarn>
	</PropertyGroup>

</Project>
