//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrashEdit.CE.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 100, 747, 560")]
        public global::System.Drawing.Rectangle FormBounds {
            get {
                return ((global::System.Drawing.Rectangle)(this["FormBounds"]));
            }
            set {
                this["FormBounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState FormWindowState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["FormWindowState"]));
            }
            set {
                this["FormWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en")]
        public string Language {
            get {
                return ((string)(this["Language"]));
            }
            set {
                this["Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public int DefaultFormW {
            get {
                return ((int)(this["DefaultFormW"]));
            }
            set {
                this["DefaultFormW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public int DefaultFormH {
            get {
                return ((int)(this["DefaultFormH"]));
            }
            set {
                this["DefaultFormH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisplayNormals {
            get {
                return ((bool)(this["DisplayNormals"]));
            }
            set {
                this["DisplayNormals"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisplayFrameCollision {
            get {
                return ((bool)(this["DisplayFrameCollision"]));
            }
            set {
                this["DisplayFrameCollision"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DeleteInvalidEntries {
            get {
                return ((bool)(this["DeleteInvalidEntries"]));
            }
            set {
                this["DeleteInvalidEntries"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplayAnimGrid {
            get {
                return ((bool)(this["DisplayAnimGrid"]));
            }
            set {
                this["DisplayAnimGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int AnimGridLen {
            get {
                return ((int)(this["AnimGridLen"]));
            }
            set {
                this["AnimGridLen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PatchNSDSavesNSF {
            get {
                return ((bool)(this["PatchNSDSavesNSF"]));
            }
            set {
                this["PatchNSDSavesNSF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-16382458")]
        public int ClearColorRGB {
            get {
                return ((int)(this["ClearColorRGB"]));
            }
            set {
                this["ClearColorRGB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpgradeSettings {
            get {
                return ((bool)(this["UpgradeSettings"]));
            }
            set {
                this["UpgradeSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public float FontSize {
            get {
                return ((float)(this["FontSize"]));
            }
            set {
                this["FontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("arial.ttf")]
        public string FontName {
            get {
                return ((string)(this["FontName"]));
            }
            set {
                this["FontName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Font3DEnable {
            get {
                return ((bool)(this["Font3DEnable"]));
            }
            set {
                this["Font3DEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Font2DEnable {
            get {
                return ((bool)(this["Font2DEnable"]));
            }
            set {
                this["Font2DEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ViewerShowHelp {
            get {
                return ((bool)(this["ViewerShowHelp"]));
            }
            set {
                this["ViewerShowHelp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.2")]
        public float NodeShadeMax {
            get {
                return ((float)(this["NodeShadeMax"]));
            }
            set {
                this["NodeShadeMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ViewZoneBox {
            get {
                return ((bool)(this["ViewZoneBox"]));
            }
            set {
                this["ViewZoneBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ViewZoneName {
            get {
                return ((bool)(this["ViewZoneName"]));
            }
            set {
                this["ViewZoneName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ViewCamera {
            get {
                return ((bool)(this["ViewCamera"]));
            }
            set {
                this["ViewCamera"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ViewCameraAngle {
            get {
                return ((bool)(this["ViewCameraAngle"]));
            }
            set {
                this["ViewCameraAngle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableVisual {
            get {
                return ((bool)(this["EnableVisual"]));
            }
            set {
                this["EnableVisual"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowEntityParams {
            get {
                return ((bool)(this["ShowEntityParams"]));
            }
            set {
                this["ShowEntityParams"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ModePAL {
            get {
                return ((bool)(this["ModePAL"]));
            }
            set {
                this["ModePAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseOldPatchNSD {
            get {
                return ((bool)(this["UseOldPatchNSD"]));
            }
            set {
                this["UseOldPatchNSD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowliteralCollisionTypes {
            get {
                return ((bool)(this["ShowliteralCollisionTypes"]));
            }
            set {
                this["ShowliteralCollisionTypes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableCustomCrates {
            get {
                return ((bool)(this["EnableCustomCrates"]));
            }
            set {
                this["EnableCustomCrates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableC2TTEditor {
            get {
                return ((bool)(this["EnableC2TTEditor"]));
            }
            set {
                this["EnableC2TTEditor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PatchGOOLC3toC2 {
            get {
                return ((bool)(this["PatchGOOLC3toC2"]));
            }
            set {
                this["PatchGOOLC3toC2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SplitAnimViewerPanels {
            get {
                return ((bool)(this["SplitAnimViewerPanels"]));
            }
            set {
                this["SplitAnimViewerPanels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AlignedMovement {
            get {
                return ((bool)(this["AlignedMovement"]));
            }
            set {
                this["AlignedMovement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableLegacyEntityBox {
            get {
                return ((bool)(this["EnableLegacyEntityBox"]));
            }
            set {
                this["EnableLegacyEntityBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MakeBinPath {
            get {
                return ((string)(this["MakeBinPath"]));
            }
            set {
                this["MakeBinPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MakeBinSavePath {
            get {
                return ((string)(this["MakeBinSavePath"]));
            }
            set {
                this["MakeBinSavePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MakeBinRegion {
            get {
                return ((int)(this["MakeBinRegion"]));
            }
            set {
                this["MakeBinRegion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DefaultGameVersion {
            get {
                return ((int)(this["DefaultGameVersion"]));
            }
            set {
                this["DefaultGameVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OutputCopyTextureResult {
            get {
                return ((bool)(this["OutputCopyTextureResult"]));
            }
            set {
                this["OutputCopyTextureResult"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OutputModelTextureInfo {
            get {
                return ((bool)(this["OutputModelTextureInfo"]));
            }
            set {
                this["OutputModelTextureInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ApplyMica {
            get {
                return ((bool)(this["ApplyMica"]));
            }
            set {
                this["ApplyMica"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OutputCLUTInfo {
            get {
                return ((bool)(this["OutputCLUTInfo"]));
            }
            set {
                this["OutputCLUTInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IgnoreDuplicatedEntryError {
            get {
                return ((bool)(this["IgnoreDuplicatedEntryError"]));
            }
            set {
                this["IgnoreDuplicatedEntryError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Small")]
        public string HexViewCellSize {
            get {
                return ((string)(this["HexViewCellSize"]));
            }
            set {
                this["HexViewCellSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowRenderingErrors {
            get {
                return ((bool)(this["ShowRenderingErrors"]));
            }
            set {
                this["ShowRenderingErrors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowRebuildUI {
            get {
                return ((bool)(this["ShowRebuildUI"]));
            }
            set {
                this["ShowRebuildUI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c2export.exe")]
        public string C2ExportPath {
            get {
                return ((string)(this["C2ExportPath"]));
            }
            set {
                this["C2ExportPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowUndockButton {
            get {
                return ((bool)(this["ShowUndockButton"]));
            }
            set {
                this["ShowUndockButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowRefreshButton {
            get {
                return ((bool)(this["ShowRefreshButton"]));
            }
            set {
                this["ShowRefreshButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\n<ArrayOfString xmlns:xsd=\"http://www.w3.o" +
            "rg/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" />")]
        public global::System.Collections.Specialized.StringCollection RecentNSFFiles {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RecentNSFFiles"]));
            }
            set {
                this["RecentNSFFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AllowMultiopenNSF {
            get {
                return ((bool)(this["AllowMultiopenNSF"]));
            }
            set {
                this["AllowMultiopenNSF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseNeighborZoneTransparency {
            get {
                return ((bool)(this["UseNeighborZoneTransparency"]));
            }
            set {
                this["UseNeighborZoneTransparency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowAnimTex0 {
            get {
                return ((bool)(this["ShowAnimTex0"]));
            }
            set {
                this["ShowAnimTex0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public byte DefaultFogValue {
            get {
                return ((byte)(this["DefaultFogValue"]));
            }
            set {
                this["DefaultFogValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DefaultFogIsActive {
            get {
                return ((bool)(this["DefaultFogIsActive"]));
            }
            set {
                this["DefaultFogIsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DefaultParticleIsActive {
            get {
                return ((bool)(this["DefaultParticleIsActive"]));
            }
            set {
                this["DefaultParticleIsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultPreset {
            get {
                return ((string)(this["DefaultPreset"]));
            }
            set {
                this["DefaultPreset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DefaultpictureBoxBackgroundTextureGapColor {
            get {
                return ((int)(this["DefaultpictureBoxBackgroundTextureGapColor"]));
            }
            set {
                this["DefaultpictureBoxBackgroundTextureGapColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DefaultRecolorGapIsActive {
            get {
                return ((bool)(this["DefaultRecolorGapIsActive"]));
            }
            set {
                this["DefaultRecolorGapIsActive"] = value;
            }
        }
    }
}
